name: Check for compile errors
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
   job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: |
          sudo apt-get -y update
          sudo apt-get -y install gcc
          sudo apt-get -y install make
          sudo apt-get -y install git
          sudo apt-get -y install nasm
          sudo apt-get -y install mtools
          sudo apt-get -y install autoconf
          sh tools/cross.sh
          ./configure
          make
