name: Check for compile errors
on: [push, pull_request]

jobs:
  build:
    name: Check for compile errors
    runs-on: ubuntu-latest

    steps:
      - name: Install deps
        run: |
          sudo apt-get -y install clang
          sudo apt-get -y install make
          sudo apt-get -y install git
          sudo apt-get -y install nasm
          sudo apt-get -y install xorriso
          sudo apt-get -y install mtools
          sudo apt-get -y install autoconf

      - name: Build cross-compiler
        run: bash tools/cross.sh

      - name: Build ZebraLoader
        run: ./configure; make
