name: Check for compile errors
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
   job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install deps
        run: |
          sudo apt-get -y update
          sudo apt-get -y install clang
          sudo apt-get -y install make
          sudo apt-get -y install git
          sudo apt-get -y install nasm
          sudo apt-get -y install mtools
          sudo apt-get -y install autoconf

      - name: Build cross-compiler
        run: bash tools/cross.sh

      - name: Build ZebraLoader
        run: ./configure; make
